### ISSUE TITLE
[Request] Common LISP

### ISSUE THREAD

**Issue by Souiken** [SAWARATSUKI/ServiceLogos#432] opened 2024-04-26 04:08 UTC
### Check for duplicates

- [X] Checked

### Service Name

Common LISP

### Comment

It is a dialect of Lisp.
Different to Racket.
refer: https://common-lisp.net/

**Comment by Sinihopea** [comment] 2024-04-26 06:22
This issue is a duplicate of:

https://github.com/SAWARATSUKI/ServiceLogos/issues/85

**Comment by SAWARATSUKI** [comment] 2024-04-29 15:48
Done!

**Closed by SAWARATSUKI** 2024-04-29 15:48 UTC
Labels: enhancement, request
