### ISSUE TITLE
[Request] php

### ISSUE THREAD

**Issue by lovefc** [SAWARATSUKI/ServiceLogos#533] opened 2024-04-28 00:53 UTC
### Check for duplicates

- [X] Checked

### Service Name

php

### Service name in Japanese

php

### Comment

Hello, php is a mainstream language, why doesn't it have its logo? Thank you first.

**Comment by goodjack** [comment] 2024-04-28 03:21
Duplicate of #65

**Comment by SAWARATSUKI** [comment] 2024-05-01 16:43
Added!!!!!

**Closed by SAWARATSUKI** 2024-05-01 16:43 UTC
Labels: enhancement, request
